language: python
python:
  - "2.6"
  - "2.7"
  # - "pypy" - won't work as smmap doesn't work (see gitdb/.travis.yml for details)

install:
  - git submodule update --init --recursive
  - git fetch --tags
  - pip install coveralls
script: 
  - nosetests --with-coverage
# after_success: as long as we are not running smoothly ... give it the cover treatment every time
  - coveralls
