language: python
python:
  - "2.6"
  - "2.7"
  # - "pypy" - won't work as smmap doesn't work (see gitdb/.travis.yml for details)

install:
  - git submodule update --init --recursive
  - git fetch --tags
script: 
  - nosetests
