language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  # - "pypy" - won't work as smmap doesn't work (see gitdb/.travis.yml for details)
git:
  # a higher depth is needed for most of the tests - must be high enough to not actually be shallow
  # as we clone our own repository in the process
  depth: 99999
install:
  - git submodule update --init --recursive
  - git fetch --tags
  - pip install coveralls flake8

  # generate some reflog as git-python tests need it (in master)
  - git checkout master
  - git reset --hard HEAD~1
  - git reset --hard HEAD~1
  - git reset --hard HEAD~1
  - git reset --hard origin/master

  # as commits are performed with the default user, it needs to be set for travis too
  - git config --global user.email "travis@ci.com"
  - git config --global user.name "Travis Runner"
script: 
  # Make sure we limit open handles to see if we are leaking them
  - ulimit -n 64
  - ulimit -n
  - nosetests -v --with-coverage
  - flake8
after_success:
  - coveralls
