language: python
python:
  - "2.6"
  - "2.7"
  # - "pypy" - won't work as smmap doesn't work (see gitdb/.travis.yml for details)
git:
  # a higher depth is needed for most of the tests - must be high enough to not actually be shallow
  # as we clone our own repository in the process
  depth: 99999
install:
  - git submodule update --init --recursive
  - git fetch --tags
  - pip install coveralls

  # generate some reflog as git-python tests need it (in 0.3)
  - git checkout 0.3
  - git reset --hard HEAD~1
  - git reset --hard HEAD~1
  - git reset --hard HEAD~1
  - git reset --hard origin/0.3
  - git checkout -b master
  - git reset --hard HEAD~1
  - git reset --hard HEAD~1
  - git reset --hard HEAD~1
  - git reset --hard origin/0.3
  - git checkout 0.3

  # as commits are performed with the default user, it needs to be set for travis too
  - git config --global user.email "travis@ci.com"
  - git config --global user.name "Travis Runner"
script: 
  - nosetests -v --with-coverage
after_success:
  - coveralls
